In [ ]:
import numpy as np

X = np.random.normal(size=[2,3])
X =np.array(X)


U, D, V = np.linalg.svd(X, full_matrices=False)
X_rec= np.dot(U, np.dot(np.diag(D), V))

###Así se hace una matriz y tengo U,D,V
### Ahora tengo que descomponerlos

V_t=np.transpose(V)




In [100]:
## Hago la pseudoinversa de la diagonal
D_diag=np.diag(D)

#D=np.array([[3,0,0],[0,0,0],[0,0,4]])



rows, col =D_diag.shape

D_inv = np.zeros((rows,col))

for i in range(0,max(rows,col)):
    if D_diag[i,i]!= 0 :
        D_inv[i,i]=1/D_diag[i,i]
    else :
        D_inv[i,i]= 0

newArray

array([[ 0.33333333,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.25      ]])

In [109]:
## Con esto ya tengo todo para hacer la pseudoinversa que es V_t*D_inv*U

pseudo = np.dot(np.dot(V_t, D_inv), U)


In [106]:
## Entonces ahora quiero hacer una función que dada una matriz A y un vector y pueda obtener
## Ax=y => x= A**y con A** la pseudoinversa de A

def pseudo (A,y):
    X=np.array(A)
    y=np.array(y)
    U, D, V = np.linalg.svd(X, full_matrices=False)
    
    V_t=np.transpose(V)
    
    D_diag=np.diag(D) 
    ## D=np.array([[3,0,0],[0,0,0],[0,0,4]]) ESTE ES DE EJEMPLO

    rows, col =D_diag.shape
    D_inv = np.zeros((rows,col))
    
    for i in range(0,max(rows,col)):
        if D_diag[i,i]!= 0 :
            D_inv[i,i]=1/D_diag[i,i]
        else :
            D_inv[i,i]= 0
    
    pseudo = np.dot(np.dot(V_t, D_inv), U)
    
    sol=pseudo*y
    print(sol)
    

In [108]:
X = np.random.normal(size=[3,2])
y= np.random.normal(size=[2,1])

pseudo(X,y)



ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [76]:
newArray

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [52]:
A

matrix([[ 1,  2,  4],
        [ 4,  5, 12]])

In [38]:
np.diag(D).shape


(2, 2)

In [20]:
U.shape

(1, 1)