# Tarea 1: alumno Jorge III Altamirano Astorga

## Introducción

Presento la siguiente tarea para la materia de Propedéutico de la Maestría en Ciencia de Datos del Instituto Tecnológico Autónomo de México. Le agradezco al Maestro Mauricio García Tec por su comprensión y por compartir conocimiento nuevo para mí.

### Importación e inicialización de arrays

import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]
x + y

#### Matrices como arrays

Presentación de matrices
```
Matríz con numpy:
[[1,2,3],[4,5,6]]
```
Corresponde a la matriz
$$
X = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6  \end{bmatrix}
$$


In [7]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

#### Operaciones con arrays

$$
X + 2B = \begin{bmatrix} 3 & 6 & 9 \\ 12 & 15 & 18 \end{bmatrix}
$$

In [11]:
X + 2*X

array([[ 3,  6,  9],
       [12, 15, 18]])

#### Multiplicación de matrices con numpy.matmul()

$$
X^t \times  X = \begin{bmatrix} 17 & 22 & 27 \\ 22 & 29 & 36 \\ 27 & 36 & 45 \end{bmatrix}
$$

In [14]:
np.matmul(X.transpose(), X) #X^t * X

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

#### Obteniendo datos específicos


In [16]:
X[1,1]

5

#### Selección y multi selección de elementos... 

$$
X = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6  \end{bmatrix}
$$

In [24]:
X[1, :] #1. Fila entera

array([4, 5, 6])

In [25]:
X[:, 1] #2. Columna entera

array([2, 5])

In [30]:
X[0:2, 0:2] #3. Slice de n:m, n,n+1,...,m-1

array([[1, 2],
       [4, 5]])

In [34]:
X.shape #Dimensión de arrays

(2, 3)

### Vectores

Numpy es *vector-ready*

In [37]:
vec = np.array([1, 2, 3])
print(vec)

[1 2 3]


## Creando clases en Python

Creando clases en Python from scratch

In [51]:
class Array:
    "Clase mínima para Álgebra Lineal"
    def __init__(self, list_of_rows):
        "Constructor"
        self.data = list_of_rows
        self.shape = (len(list_of_rows), len(list_of_rows[0]))

In [65]:
A = Array([[1, 2, 3], [4, 5, 6]])
A.__dict__ # la propiedad oculta *dict* muestra las propiedades internas de la clase

{'data': [[1, 2, 3], [4, 5, 6]], 'shape': (2, 3)}

In [69]:
A.data #accediendo a la propiedad *data* de la clase

[[1, 2, 3], [4, 5, 6]]

In [70]:
A.shape #accediendo a la propiedad *shape* de la clase

(2, 3)

... *implementando métodos que faciliten la utilización de dicha clase para nuestros fines de Álgegra Lineal*

#### Métodos especiales de clase

##### 1. Método de *Pretty Print*

He aquí el método para imprimir bonito, primero mostramos como se imprime por default sin existir el método

In [72]:
Array([[1,2,3], [4,5,6]])

In [73]:
print(Array([[1,2,3], [4,5,6]]))

In [77]:
# Prueba de clase
class JorgeClass:
    def __init__(self):
        pass # para no hacer nada
    def say_hi(self):
        print("¡Método de impresión simple!")
    def __repr__(self):
        return "Representación sin imprimir nada"
    def __str__(self):
        return "Método explícito para *print* como objeto"

In [78]:
x = JorgeClass()
x.say_hi()

¡Método de impresión simple!


In [79]:
x

Representación sin imprimir nada

In [80]:
print(x)

Método explícito para *print* como objeto


### <span style="color: red"> EJERCICIO 1 </span>

#### Validador